// tab space = 4
/***********************************************************************/
/*                                                                     */
/*  FILE        :main_qsk26a_template.c                                 */
/*  DATE        :July 6, 2004	                                       */
/*  DESCRIPTION :Main Program                                          */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.3.1).     */
/*                                                                     */
/***********************************************************************/
                  
#include "qsk_bsp.h"	 // include QSK board support package
#include "mcu_init.h"
#include "spi_init.h"
#include "serial.h"

extern unsigned char new_sample, buff[4];			// if 1, initiates writes/reads 
unsigned char up_down, wrt_value, rd_value;		   		// 0: count down, 1:count up 
unsigned int i=0, addr=0;
extern Q_T tx_q, rx_q;

/******************************************************************************
Name       : main
Parameters : none
Returns    : nothing
Description: Main template
******************************************************************************/
void main(void)
{
	mcu_init();			// Initialize MCU
	
	up_down = 1;  new_sample = 0; wrt_value = 97; // Initialize control values. 
	addr = 0x001C;
	// initialize timer and SPI interface 
	spi_init();
	//init_UART0();
  	//Q_Init(&tx_q);
  	//Q_Init(&rx_q);
	
	//Init_Sampling();
	ENABLE_IRQ; 		// Enable global interrupts
	
	for(i=0;i<5000;i++){
		//if(new_sample){						// time to get new sample?
			delay(65535);
			YLW_LED = LED_ON;
			new_sample = 0;			
		//	spi_write(wrt_value, addr);		// Write new pot value
			_asm("nop");
			delay(65535);
			rd_value = spi_read(addr);	// Read current pot value
			
		/*	if(up_down){ 					// 1? then count up	    
				++wrt_value;			// increment wrt_pot_value
				if(wrt_value > 122)		  
					up_down = 0;
			}
			else { 							// 0 so count down
				--wrt_value;			// decrement wrt_pot_value. 
				if(wrt_value == 97)
					up_down = 1;
			}	*/		
		//}
		delay(65535);		
		YLW_LED = LED_OFF;
		RED_LED = LED_OFF;
		GRN_LED = LED_OFF;		
		/*delay(65535);
		send_string("here\n\r");
		delay(65535);
		YLW_LED = LED_OFF;		
		Q_Init(&tx_q);	
		delay(65535);*/	
	 }
	GRN_LED = LED_ON;
}
