function formankin()

[piezo ir mic] = time_domain('roach1.mat',5);
save('Ro1.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach2.mat',5);
save('Ro2.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach3.mat',5);
save('Ro3.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach5.mat',5);
save('Ro5.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach7.mat',5);
save('Ro7.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach8.mat',5);
save('Ro8.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach9.mat',5);
save('Ro9.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach10.mat',5);
save('Ro10.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach11.mat',5);
save('Ro11.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach12.mat',5);
save('Ro12.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach13.mat',5);
save('Ro13.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach14.mat',5);
save('Ro14.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach15.mat',5);
save('Ro15.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach16.mat',5);
save('Ro16.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach17.mat',5);
save('Ro17.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach18.mat',3);
save('Ro18.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach19.mat',3);
save('Ro19.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('roach20.mat',3);
save('Ro20.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant1.mat',5);
save('An1.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant2.mat',5);
save('An2.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant3.mat',5);
save('An3.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant4.mat',5);
save('An4.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant6.mat',3);
save('An6.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant7.mat',3);
save('An7.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant8.mat',3);
save('An8.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant9.mat',3);
save('An9.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant10.mat',3);
save('An10.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant11.mat',3);
save('An11.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant12.mat',3);
save('An12.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant13.mat',3);
save('An13.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant14.mat',3);
save('An14.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant15.mat',3);
save('An15.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant17.mat',3);
save('An17.mat','piezo','ir','mic');
[piezo ir mic] = time_domain('ant19.mat',3);
save('An19.mat','piezo','ir','mic');